### PR TITLE
文档维护

### PR DESCRIPTION
**Pull request by FANminiworld**

### CODE REVIEW

**Comment by U-v-U** [comment]
The QR export is not yet removed.

**Comment by FANminiworld** [comment]
If the QR code function is removed, then merge this Pull request again

**Comment by U-v-U** [comment]
@FANminiworld The QRCode generation will still be with Qv2ray until a working Android version is out.

**Comment by FANminiworld** [comment]
Suggest removing QR code related features at the earliest possible time (wrong)

**Comment by U-v-U** [comment]
Since we are moving translations onto the Crowdin Platform, we now only accept English source PRs.
Feel free to reopen with an updated English version.

**Pull request closed without merging**
