### PR TITLE
Update faq/v2ray-core.md

### PR DESCRIPTION
**Pull request by sixg0000d**
Translate from en/faq/v2ray-core.md.

### CODE REVIEW

**Comment by sixg0000d** [comment]
终于~~抄~~写完了，内容太长不敢直接合并，还请~~鸭老大~~审批。
ps. 感觉[这里](https://qv2ray.net/en/faq/#v2ray-core-failed-to-start)和[这里](https://qv2ray.net/en/faq/v2ray-core.html#cannot-listen-on-address)内容有所重复，要不要重新排版一下？

**Comment by U-v-U** [comment]
For now, just make sure the doc is 100% synced between en_US and zh_CN, other refactoring may happen later.

**Comment by sixg0000d** [comment]
> For now, just make sure the doc is 100% synced between en_US and zh_CN, other refactoring may happen later.

Okay.
The commit content is 99% synced from en_US (the 1% is someplace I think it is easier for users to understand after some changes). so, merge it first?

**Comment by U-v-U** [comment]
@sixg0000d Cool, and go

**Pull request merged**
